import React, { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Save } from 'lucide-react';
import { MainLayout } from '../components/layout/MainLayout';
import { PageContainer } from '../components/layout/PageContainer';
import { cafeService } from '../services/cafeService';
import { ownerService } from '../services/ownerService';
import { ownerCafeService } from '../services/ownerCafeService';
export default function OwnerCafeAmenitiesPage(){const{id}=useParams<{id:string}>();const[name,setName]=useState('');const[amenities,setAmenities]=useState<any[]>([]);const[selected,setSelected]=useState<string[]>([]);const[message,setMessage]=useState('');const[saving,setSaving]=useState(false);useEffect(()=>{if(!id)return;Promise.all([ownerService.getOwnedCafe(id),cafeService.getAmenities()]).then(([c,a])=>{setName(c.data.name);setSelected(c.data.amenities?.map((item:any)=>item.amenityId||item.amenity?.id)||[]);setAmenities(a.data)}).catch(e=>setMessage(e.message))},[id]);const save=async()=>{if(!id)return;setSaving(true);try{await ownerCafeService.updateAmenities(id,selected);setMessage('Amenities updated successfully.')}catch(e:any){setMessage(e.message)}finally{setSaving(false)}};return <MainLayout><PageContainer className="py-12"><Link to={`/owner/cafes/${id}`} className="inline-flex items-center gap-2 text-sm text-brand-muted"><ArrowLeft className="h-4 w-4"/>Back to {name}</Link><div className="mt-8 max-w-3xl"><h1 className="text-4xl font-serif font-bold">Amenities</h1>{message&&<p className="mt-4 rounded-xl bg-brand-cream p-4 text-brand-coffee">{message}</p>}<div className="mt-8 grid sm:grid-cols-2 gap-3 rounded-2xl border border-brand-border bg-white p-6">{amenities.map(item=><label key={item.id} className="flex items-center gap-3 rounded-xl border p-4"><input type="checkbox" checked={selected.includes(item.id)} onChange={e=>setSelected(value=>e.target.checked?[...value,item.id]:value.filter(id=>id!==item.id))}/><span>{item.name}</span></label>)}</div><button onClick={save} disabled={saving} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-brand-coffee px-5 py-3 font-semibold text-white"><Save className="h-4 w-4"/>{saving?'Saving...':'Save amenities'}</button></div></PageContainer></MainLayout>}
