import React, { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Save } from 'lucide-react';
import { MainLayout } from '../components/layout/MainLayout';
import { PageContainer } from '../components/layout/PageContainer';
import { ownerService } from '../services/ownerService';
import { ownerCafeService, OwnerHours } from '../services/ownerCafeService';

const days = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
export default function OwnerCafeHoursPage() { const { id } = useParams<{ id: string }>(); const [name,setName]=useState(''); const [hours,setHours]=useState<OwnerHours[]>(days.map((_,dayOfWeek)=>({dayOfWeek,isClosed:false,openTime:'08:00',closeTime:'20:00'}))); const [message,setMessage]=useState(''); const [saving,setSaving]=useState(false); useEffect(()=>{if(id) ownerService.getOwnedCafe(id).then(r=>{setName(r.data.name); if(r.data.hours?.length===7)setHours(r.data.hours);}).catch(e=>setMessage(e.message));},[id]); const set=(index:number, patch:Partial<OwnerHours>)=>setHours(value=>value.map((hour,i)=>i===index?{...hour,...patch}:hour)); const save=async()=>{if(!id)return;setSaving(true);try{await ownerCafeService.updateHours(id,hours);setMessage('Business hours updated successfully.');}catch(e:any){setMessage(e.message)}finally{setSaving(false)}}; return <MainLayout><PageContainer className="py-12"><Link to={`/owner/cafes/${id}`} className="inline-flex items-center gap-2 text-sm text-brand-muted"><ArrowLeft className="h-4 w-4"/>Back to {name}</Link><div className="mt-8 max-w-3xl"><h1 className="text-4xl font-serif font-bold">Business hours</h1>{message&&<p className="mt-4 rounded-xl bg-brand-cream p-4 text-brand-coffee">{message}</p>}<div className="mt-8 divide-y rounded-2xl border border-brand-border bg-white">{hours.map((hour,index)=><div key={hour.dayOfWeek} className="grid gap-3 p-4 sm:grid-cols-[8rem_1fr_1fr_auto] sm:items-center"><strong>{days[hour.dayOfWeek]}</strong><input type="time" disabled={hour.isClosed} value={hour.openTime||''} onChange={e=>set(index,{openTime:e.target.value})} className="rounded-lg border p-2"/><input type="time" disabled={hour.isClosed} value={hour.closeTime||''} onChange={e=>set(index,{closeTime:e.target.value})} className="rounded-lg border p-2"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={hour.isClosed} onChange={e=>set(index,{isClosed:e.target.checked})}/> Closed</label></div>)}</div><button onClick={save} disabled={saving} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-brand-coffee px-5 py-3 font-semibold text-white"><Save className="h-4 w-4"/>{saving?'Saving...':'Save hours'}</button></div></PageContainer></MainLayout>; }
