import React, { useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, CheckCircle2 } from 'lucide-react';
import { adminClaimService } from '../../services/adminClaimService';
import { OwnerClaim } from '../../services/ownerClaimService';

export default function AdminOwnerClaimDetailsPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [claim, setClaim] = useState<OwnerClaim | null>(null);
  const [reason, setReason] = useState('');
  const [error, setError] = useState('');
  useEffect(() => { if (id) adminClaimService.getClaim(id).then(result => setClaim(result.data)).catch(err => setError(err.message)); }, [id]);
  const approve = async () => { if (!id || !window.confirm('Approve this claim and assign ownership?')) return; try { await adminClaimService.approveClaim(id); navigate('/admin/claims'); } catch (err: any) { setError(err.message); } };
  const reject = async () => { if (!id || reason.trim().length < 5) { setError('A rejection reason of at least 5 characters is required.'); return; } try { await adminClaimService.rejectClaim(id, reason); navigate('/admin/claims'); } catch (err: any) { setError(err.message); } };
  const reopen = async () => { if (!id || !window.confirm('Reopen this claim?')) return; try { await adminClaimService.reopenClaim(id); setClaim((await adminClaimService.getClaim(id)).data); } catch (err: any) { setError(err.message); } };
  return <div className="max-w-4xl space-y-6"><Link to="/admin/claims" className="inline-flex items-center gap-2 text-sm text-stone-500"><ArrowLeft className="h-4 w-4" /> Back to claims</Link>{error && <p className="rounded-lg bg-red-50 p-4 text-red-700">{error}</p>}{!claim ? <p className="text-stone-500">Loading claim...</p> : <><div><p className="text-xs font-bold uppercase tracking-widest text-amber-600">Owner claim</p><h1 className="mt-2 text-3xl font-bold text-stone-900">{claim.cafe.name}</h1><span className="mt-3 inline-block rounded-full bg-stone-100 px-3 py-1 text-xs font-bold uppercase">{claim.status}</span></div><div className="grid md:grid-cols-2 gap-5"><section className="rounded-xl border border-stone-200 bg-white p-6 space-y-3"><h2 className="font-bold">Claimant</h2><p>{claim.user?.name}</p><p className="text-sm text-stone-500">{claim.user?.email}</p><p className="text-sm text-stone-500">Business: {claim.businessName}</p></section><section className="rounded-xl border border-stone-200 bg-white p-6 space-y-3"><h2 className="font-bold">Contact</h2><p>{claim.contactName || 'No contact name'}</p><p className="text-sm text-stone-500">{claim.contactEmail || 'No email supplied'}</p><p className="text-sm text-stone-500">{claim.contactPhone || 'No phone supplied'}</p></section></div><section className="rounded-xl border border-stone-200 bg-white p-6"><h2 className="font-bold">Authorization message</h2><p className="mt-3 whitespace-pre-wrap text-stone-600">{claim.message || claim.verificationInformation || 'No message supplied.'}</p></section>{claim.status === 'PENDING' && <section className="rounded-xl border border-stone-200 bg-white p-6 space-y-4"><div className="flex flex-wrap gap-3"><button onClick={approve} className="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-4 py-2 font-semibold text-white"><CheckCircle2 className="h-4 w-4" /> Approve</button></div><label className="block text-sm font-semibold">Rejection reason<textarea value={reason} onChange={e => setReason(e.target.value)} rows={4} className="mt-2 w-full rounded-lg border border-stone-200 p-3" /></label><button onClick={reject} className="rounded-lg bg-red-600 px-4 py-2 font-semibold text-white">Reject claim</button></section>}{(claim.status === 'REJECTED' || claim.status === 'CANCELLED') && <button onClick={reopen} className="rounded-lg bg-stone-900 px-4 py-2 font-semibold text-white">Reopen claim</button>}</>}</div>;
}
